kind: pipeline
name : neXus
steps:
 - name: SDM660
   image: xyzuan/xdocker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - git clone --depth=1 https://github.com/Ahaduzzaman2020/kernel_xiaomi_lavender.git XD
     - cd XD
     - bash build.sh