kind: pipeline
name : xKernel Compiler
version: rev1.5_template
steps:
 - name: xKernel Compilation
   image: xyzuan/xdocker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - git clone --depth=1 https://github.com/NotZeetaa/nexus_kernel_lavender lavender
     - cd lavender
     - bash .circleci/build.sh
